### ISSUE TITLE
Is this still usable with paid Twitter access?

### ISSUE THREAD

**Issue by banajana** [DocNow/hydrator#148]
Will Hydrator work if I'm paying Twitter the $100/month package? I installed it, but the 'Link Twitter Account' button is non-responsive.

**Comment by edsu** [comment]
Not unless you rebuild it with your own api application keys. I would recommend you use twarc instead since it makes it easier to set these. Hydrator was always supposed to be an easier to use tool since it didn't require cresting your own developer application and users could simply use their user account login to use it. But those days are over since Twitter revoked the keys that it used.
