### ISSUE TITLE
51% hydration rate? 

### ISSUE THREAD

**Issue by norcalbiostat** [DocNow/hydrator#31]
I'm getting a very unreasonably poor hydration rate for the ID's found in a COVID-19 dataset https://github.com/echen102/COVID-19-TweetIDs 

Their readme states that @edsu was only missing 6% due to deletions. As the title implies, i'm getting substantially poorer rate. 

I passed a batch of ID's that didn't hydrate the first time back through again, and 12% were successfully hydrated on a second pass. 

I'm not understanding where the 'leak' is. 

I am assigning this task to non-technical students, and so using twarc is not an option for them.

**Comment by edsu** [comment]
Thanks for reaching out about this @norcalbiostat. 51% hydration rate is very low indeed. Your observation about being able to hydrate previously unhydratable ids is also worrisome. That being said, I know that platforms are dealing with a huge amount of COVID-19 related disinformation, so it is within the realm of possibility that this amount of data is being deleted, and that content may be restored.

I started my hydration process immediately after the v1 dataset was released (8,306,997 tweets). If I'm remembering right @echen102 and her team released the most recent data first. So I was hydrating the most recent tweets. As data gets older it typically stands a higher chance of being deleted.

Are you hydrating v1.2 (72,403,796)? Did you concatenate the ids into one file in order to give them to the Hydrator? I hope that Excel or another tool wasn't involved in the process since it is quite easy to [overflow](https://developer.twitter.com/en/docs/basics/twitter-ids) tweet identifiers if you are not careful.

If you are game I'd like to conduct a test with the tweets from 2020-01-26 and hydrate with Hydrator and twarc to make sure that I'm seeing the same sort of deletion rate for both tools. Do you think there would be value in me doing that?

So I will look at these tweet ids:

```
   $ wc -l 2020-01/*2020-01-26*.txt
   47450 2020-01/coronavirus-tweet-id-2020-01-26-00.txt
   51336 2020-01/coronavirus-tweet-id-2020-01-26-01.txt
   55143 2020-01/coronavirus-tweet-id-2020-01-26-02.txt
   59115 2020-01/coronavirus-tweet-id-2020-01-26-03.txt
   57551 2020-01/coronavirus-tweet-id-2020-01-26-04.txt
   55244 2020-01/coronavirus-tweet-id-2020-01-26-05.txt
   52344 2020-01/coronavirus-tweet-id-2020-01-26-06.txt
   53390 2020-01/coronavirus-tweet-id-2020-01-26-07.txt
   55627 2020-01/coronavirus-tweet-id-2020-01-26-08.txt
   52656 2020-01/coronavirus-tweet-id-2020-01-26-09.txt
   52898 2020-01/coronavirus-tweet-id-2020-01-26-10.txt
   56157 2020-01/coronavirus-tweet-id-2020-01-26-11.txt
   58261 2020-01/coronavirus-tweet-id-2020-01-26-12.txt
   65588 2020-01/coronavirus-tweet-id-2020-01-26-13.txt
   72685 2020-01/coronavirus-tweet-id-2020-01-26-14.txt
   76308 2020-01/coronavirus-tweet-id-2020-01-26-15.txt
   72056 2020-01/coronavirus-tweet-id-2020-01-26-16.txt
   60876 2020-01/coronavirus-tweet-id-2020-01-26-17.txt
   51686 2020-01/coronavirus-tweet-id-2020-01-26-18.txt
   50571 2020-01/coronavirus-tweet-id-2020-01-26-19.txt
   51072 2020-01/coronavirus-tweet-id-2020-01-26-20.txt
   49097 2020-01/coronavirus-tweet-id-2020-01-26-21.txt
   47936 2020-01/coronavirus-tweet-id-2020-01-26-22.txt
   51133 2020-01/coronavirus-tweet-id-2020-01-26-23.txt
 1356180 total
```



Could you point to a specific file in the dataset that you are loading that I can test with? I'm assuming that

**Comment by norcalbiostat** [comment]
> huge amount of COVID-19 related disinformation

You do have a point there. I wasn't thinking about that with regards to removed tweets. 

> Are you hydrating v1.2 (72,403,796)? 

Yes, i'm programmatically sampling hours out of time frames that they have posted, reading the text file directly from the URL, and then sampling 200 id's from within that file.  I only started this project 'at scale' perhaps a week ago. 

> Did you concatenate the ids into one file in order to give them to the Hydrator? 

I am using R to do the sampling, and concatenating, then writing out to a plain .txt file. The files only contain about 5000 or so because of a problem i ran into below that i can't quite figure out

> it is quite easy to overflow tweet identifiers if you are not careful

I wonder if this is why in the text file some numbers were being displayed as E+18, even though in R itself it would display all digits. I have been manually (yes i know) going through the text files with `ctrl+F` and deleting those records. Out of a batch of 5000 ish ID's, perhaps 20 are removed prior to hydration due to this glitch (that's probably on my end). I'm not using anything other than R and notepad. 

> If you are game I'd like to conduct a test with the tweets from 2020-01-26

I'm game for a test like this, but with the above issue of having to manually filter through to remove E+, doing 1.3M that's too time consuming. I've gotten faster at keyboard shortcuts to find/select row/delete, but this would still take me hours or so to do and right now i don't have that kinda time. 

I could do a smaller subset, like two hours, or i could send you the text file of ID's that wouldn't hydrate on my end. If you can hydrate them using twarc, that'll tell us at least something.

**Comment by edsu** [comment]
Thanks for those details! If you share the ID file that you generated I can take a look at it. One hint that the IDs have overflowed is if they all end in 0.

It's just one day, but I just rehydrated the 2020-01-26 ID files with Hydrator and got a 13% delete rate, which is much more along the lines of what I would expect to see.

<img width="612" alt="Screen Shot 2020-04-09 at 12 35 31 PM" src="https://user-images.githubusercontent.com/33829/78918978-394c3980-7a5f-11ea-8b4a-eca9efc813f9.png">

**Comment by norcalbiostat** [comment]
all end in 0 huh? That gives me some ideas to try. 
I'll send you my text file to your pobox mail listed on your GH profile.

**Comment by edsu** [comment]
Well just to be clear, the IDs should NOT all end in 0. That's an indicator that an overflow has occurred.

I'm not an R programmer unfortunately, but a little bit of Googling around leads me to believe that R has different integer types, and that the default is 32bit, which would not work with a Tweet ID. One way of working with this is to read and write them as strings instead of numbers. Or maybe you can use R's bigint?

**Comment by norcalbiostat** [comment]
i'll look into bigint, hadn't heard of that one. 
I did use sprintf to write the number with full digits as a string, but the resulting text file had "quotes" around the number, which the hydrator wouldn't have anything to do with.

**Comment by edsu** [comment]
Yea, the Hydrator wants just numbers. If you send your R code (attach here) I can take a look. But apart from that it's pretty hard for me to diagnose what's going on since you aren't hydrating the supplied id files directly.

**Comment by niall-consci** [comment]
Thank you for asking this question as I was having a similar issue. I think my problem was that I was using excel to save my txt file. I've now been able to hydrate tweets from 2020-03-28 using R and hydrator with only an 8% delete rate. Below I have added the R code I used to save the IDs to a txt file. 

`stringsAsFactors = FALSE 
df <- read.table(gzfile("2020-03-28_clean-dataset.tsv.gz"))

df <- df[-c(1), ]
df_save <- df$V1
write.table(df_save, 'textfile.txt', col.names = F, row.names = F, quote = F, sep = ' ')`

**Comment by edsu** [comment]
@norcalbiostat can we can call this issue resolved?

**Comment by norcalbiostat** [comment]
Yes - thanks for confirming that twarc received the same deletion rate, and that these older tweets are indeed being removed. You made a good point about the misinformation rate being high. 

@niall-consci  - you're exporting the ID's in the same manner that I was. Try converting `df$V1` to a vector before exporting. I still ended up with overflow numbers (E+18) in the text file, but that's a separate issue.

**Comment by abhijit-z** [comment]
Hi,
Can anyone please tell me how to use the .tsv.gz file in hydrator app (My app)? Is this approach even right?
I have got twitter dataset in .tsv.gz format and want only English language tweets.
When I select tweet ID file in the app it throws invalid message.

**Comment by edsu** [comment]
@abhijit-z Hydrator expects to be given an uncompressed text file which contains a single tweet id on each line.
