### ISSUE TITLE
Limit of records

### ISSUE THREAD

**Issue by Nabilah95** [DocNow/hydrator#58]
Hi, I want to know the limitation of records that Hydrator can hydrate. Will I be able to hydrate a total amount of 125,680,841 Twitter API?

**Comment by edsu** [comment]
I just hydrated 32 million ok. It took about a week but i didn't run it continuously. I did notice it periodically stopped hydrating. I relinked the account and then things started working again. For 125 million you might want to use twarc on a server, that doesn't turn off. But hydrator should work too.

**Comment by Nabilah95** [comment]
> I just hydrated 32 million ok. It took about a week but i didn't run it continuously. I did notice it periodically stopped hydrating. I relinked the account and then things started working again. For 125 million you might want to use twarc on a server, that doesn't turn off. But hydrator should work too.

Thank you for responding, may I know what the RAM of your laptop? Is it 4, 8 or 16 GB RAM?

**Comment by edsu** [comment]
8GB,  but RAM shouldn't be an issue. It is mostly network bound. Definitely use the latest version of the Hydrator (v0.0.13) since it fixes a CPU performance issue that was in some of the earlier versions.You may want to try a smaller dataset to see how it goes before committing to hydrating such large dataset. You wi also want to make sure you have enough available disk space.On Aug 26, 2020 10:11 PM, Nabilah95 <notifications@github.com> wrote:

I just hydrated 32 million ok. It took about a week but i didn't run it continuously. I did notice it periodically stopped hydrating. I relinked the account and then things started working again. For 125 million you might want to use twarc on a server, that doesn't turn off. But hydrator should work too.

Thank you for responding, may I know what the RAM of your laptop? Is it 4, 8 or 16 GB RAM?
