### ISSUE TITLE
Multiple Accounts?

### ISSUE THREAD

**Issue by Shooter3k** [DocNow/hydrator#74]
Is there any way to link Hydrator to multiple accounts? If not, is there any way to run Hydrator multiple times with different linked accounts?

**Comment by edsu** [comment]
Not really. You could run the Hydrator on different computers with different accounts. You may want to take a look at [twarc](https://github.com/docnow/twarc) if you want to get more fancy with how you are hydrating data. It allows you to have multiple profiles and to run concurrent processes. I would suggest that you use the same app with different authenticating users though since Twitter may be on the lookout for multiple apps (consumer key / secret pairs) at the same IP address.
